### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-react#1]
Need a `<Select>` component:

- Styles using [availity-uikit@v3](https://availity.github.io/availity-uikit/v3/)
- Integration with [availity-reactstrap-validation](https://github.com/Availity/availity-reactstrap-validation)
- Until https://github.com/JedWatson/react-select/pull/1237 is resolved use [TheSharpieOne/react-select](https://github.com/TheSharpieOne/react-select)

**Comment by TheSharpieOne** [comment]
availity-uikit doesn't have any special styles for select other than the default HTML select element. react-select and others like it are more complex and require additional styles which I wouldn't put into availity-uikit as they are very specific to the particular implementation.

I'll take this task as I already have a component which integrates react-select with availity-reactstrap-validation.

**Comment by TheSharpieOne** [comment]
released as `@availity/reactstrap-validation-select`
