### ISSUE TITLE
add user's email address to default feedback payload

### ISSUE THREAD

**Issue by nylon22** [Availity/availity-react#106]
to be clear, this is currently possible with the `staticFields` prop: https://github.com/Availity/availity-react/blob/master/packages/feedback/FeedbackForm.js#L46

I'm proposing that this info be standard

**Comment by TheSharpieOne** [comment]
IIRC, the API call is made in the context of the current user (it currently tracks the user and the region and things like that.)
Now if the underlying API changed (such as going to the datalake), that may not be the case anymore.

**Comment by nylon22** [comment]
> IIRC, the API call is made in the context of the current user (it currently tracks the user and the region and things like that.)
> Now if the underlying API changed (such as going to the datalake), that may not be the case anymore.

@TheSharpieOne Unreal you remember that 👏 You're right. I checked and the log messages api automatically enriches the log message with the requesting user's email address.
