### ISSUE TITLE
CheckboxGroup, Checkbox checked prop

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#1110]
## ❓Question

Example for dynamic checked prop. 
 ```
<CheckboxGroup
      name="checkboxGroup"
      helpId={helpId}
      label="Checkbox Group"
      required={required}
      labelClassName={labelClassName}
    >
      <Checkbox groupName="checkboxGroup" label="Check One" value="uno" />
      <Checkbox groupName="checkboxGroup" label="Check Two" value="dos" />
      <Checkbox groupName="checkboxGroup" label="Check Three" value="tres" />
    </CheckboxGroup>
```

I have tried adding `checked={myProp}` to either `CheckboxGroup` or `Checkbox`.
I'm trying to have a checkbox that will check other checkboxes, like check all toggle.

**Comment by jordan-a-young** [comment]
The values of fields are controlled by the `formik` context. Have you tried setting the values of the checkbox with the `useFormikContext` hook?

**Comment by diegodesouza** [comment]
I have not, let me try that. thanks @jordan-a-young
