### ISSUE TITLE
Pagination | Next and Prev text buttons

### ISSUE THREAD

**Issue by adenflorian** [Availity/availity-react#145]
My PO and QA would like to be able to display "Prev" and "Next" on the previous and next buttons instead of just a caret.

Something like one of these:

![image](https://user-images.githubusercontent.com/3533988/58731779-58952780-83b5-11e9-9acb-918007b376ee.png)

![image](https://user-images.githubusercontent.com/3533988/58731629-de64a300-83b4-11e9-8a98-bb8f017140b4.png)

I can do the PR, just want to check ahead of time to see y'all's thoughts and if you'd want it to be optional or not.

Thanks!

**Comment by GoPro16** [comment]
I think its a good idea in general. However, if we add this prop, every app thereafter on the portal could look different from the others, throwing off the general feel of the whole unified theme we are trying to go for.

As far as accessibility we already the aria attributes are built into the reactstrap components so we don't have to worry about making any updates to that.

I am not sure what other thoughts may be but if this doesn't matter about the them across the portal this is fine. @robmcguinness @nylon22

**Comment by robmcguinness** [comment]
having the text labels is preferred default option and probably better for accessibility. I vote to refactor the component to always include the labeled text.

@AdenFlorian please submit PR.
