### ISSUE TITLE
Add SpacesGhostText component to spaces package

### ISSUE THREAD

**Issue by nylon22** [Availity/availity-react#152]
- implement ghosting features.
    - The metadata keys are:
        - ghostText (the text to display)
        - ghostParents (csv of parent ids for the ghosted space)
        - ghosted (true/false)
    - The html markup for ghosting is:
```html
<small className="ghost-text">
     <em>{ghost-text-here}</em>
 </small>
```

**Comment by nylon22** [comment]
There are too many different ways we render spaces links that making a `<SpacesLink />` component doesn't seem practical because it wouldn't be flexible enough. i still think making a `<GhostText />` component would be useful, however.

**Comment by robmcguinness** [comment]
ghost? 👻 as in bs4 outline buttons and links?

**Comment by nylon22** [comment]
> ghost? 👻 as in bs4 outline buttons and links?

Yeah - with bs4 probably [don't need own css class](https://github.com/Availity/availity-uikit/issues/230)

IMO - the real value will be in having a shared place of _when_ and _how_ to show ghost text, powered by the space's metadata.
