### ISSUE TITLE
Add a local storybook

### ISSUE THREAD

**Issue by adrian-santos** [Availity/availity-react#178]
Can we add a local `storybook`?

https://github.com/airbnb/react-dates#live-playground is an example, so we can run the storybook locally just in case we're going to add a component

**Comment by nylon22** [comment]
https://github.com/Availity/availity-react/blob/master/package.json#L19
https://github.com/Availity/availity-react/blob/master/packages/docs/package.json#L9

`npm start` already runs storybook locally. Maybe we should add a note to the README
