### ISSUE TITLE
Remove lodash dependency in reactstrap-validation-select

### ISSUE THREAD

**Issue by nylon22** [Availity/availity-react#187]
https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-select/package.json#L44

https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-select/AvSelect.js#L6-L8

Swap for `lodash.get`, `lodash.find`, `lodash.isequal` packages

**Comment by robmcguinness** [comment]
I wonder if we really need `find` and `isequal` from lodash.
