### ISSUE TITLE
AvDateRange button still activates when disabled

### ISSUE THREAD

**Issue by adrian-santos** [Availity/availity-react#192]
When I pass on the `disabled` props, the calendar can still be activated. Just checking if this is valid since the calendar button color is also disabled. 

![Disabled](https://user-images.githubusercontent.com/17089609/60734170-09469780-9f1d-11e9-929b-7f62262dffc3.gif)

**Comment by nylon22** [comment]
should be resolved with v3 of `reactstrap-validation-date`. Please reopen if not
