### ISSUE TITLE
Datepicker component

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-react#2]
Need a `<Datepicker>` component:

- Styles using [availity-uikit@v3](https://availity.github.io/availity-uikit/v3/)
- Integration with [availity-reactstrap-validation](https://github.com/Availity/availity-reactstrap-validation)
- Integration with one of the following: 
    - [YouCanBookMe/react-datetime](https://github.com/YouCanBookMe/react-datetime)
    - [Adphorus/react-date-range](https://github.com/Adphorus/react-date-range)
    - [Hacker0x01/react-datepicker](https://github.com/Hacker0x01/react-datepicker)

**Comment by TheSharpieOne** [comment]
I have been using https://github.com/Adphorus/react-date-range as it has both single date and date range support. That in combination with reactstrap's Popover allows it to be shown/hid with a calendar button.

**Comment by TheSharpieOne** [comment]
Committed in fe7a1aaa0a and Released in v1.4.0
