### ISSUE TITLE
reactstrap-validation-date Failed prop type: CalendarWeek Warnings

### ISSUE THREAD

**Issue by jeffski13** [Availity/availity-react#249]
I am using `v3.1.1` of `reactstrap-validation-date`. 
When I click on the date picker start date i get the following warning

```Warning: Failed prop type: CalendarWeek: invalid value TypeError: CalendarWeek: invalid value supplied to 0.,TypeError: `CalendarWeek` only accepts children of type withStyles(CalendarDay),TypeError: `CalendarWeek` only accepts children of type withStyles(CustomizableCalendarDay) supplied to required children.```

My implementation is here: 
```
<AvDateRangeField
              name="dateRange"
              aria-label="date-range"
              start={{name: 'date.start'}}
              end={{name: 'date.end'}}
              min="01/01/2019"
              max={maxDate.format('MM/DD/YYYY')}
              distance={{max: {value: 1, units: 'month'}}}
              defaultValues={{start: {value: -32, units: 'days'}, end: {value: -1, units: 'days'}}}
              validate={{
                required: {
                  errorMessage: 'This field is required',
                },
              }}
            />```

**Comment by GoPro16** [comment]
We use `react-hot-loader` with `availity-workflow` so until the below issue is resolved this warning will continue.

https://github.com/airbnb/react-dates/issues/950

**Comment by diegodesouza** [comment]
I suggest looking into the solution proposed here https://github.com/airbnb/prop-types/issues/39
