### ISSUE TITLE
AvDateRange custom range object throws prop type warning

### ISSUE THREAD

**Issue by andrectoi** [Availity/availity-react#26]
I'm currently getting a failed prop type warning when trying to use a custom ranges object like below:

```Javascript
<AvDateRangeField
  label="Application Date Range"
  name="dateRange"
  start={{ name: 'dateRange.start' }}
  end={{ name: 'dateRange.end' }}
  distance={{
    min: {
      value: 1,
      units: 'days',
    },
  }}
  ranges={{
    Yesterday: {
      startDate: now => now.add(-1, 'd'),
      endDate: now => now,
    },
    'Last 7 Days': {
      startDate: now => now.add(-6, 'd'),
      endDate: now => now,
    },
    'Last 1 Month': {
      startDate: now => now.add(-1, 'M'),
      endDate: now => now,
    },
    'Last 6 Months': {
      startDate: now => now.add(-6, 'M'),
      endDate: now => now,
    },
  }}
/>
```

The resulting warning:
`checkPropTypes.js:19 Warning: Failed prop type: Invalid prop 'ranges' of type 'object' supplied to 'AvDateRange', expected 'array'.`

The code seems to work and based on the docs the ranges prop can be either an array or an object. Maybe there is something wrong with the formatting of my ranges object?

Thanks in advance!

**Comment by TheSharpieOne** [comment]
It is supposed to accept array or and object. I have updated the propType definition for that prop to reflect that.

A new version with this change will be published shortly.
