### ISSUE TITLE
AvSelectField | Label Ts Def Type should be of Type String or ReactType

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-react#279]
https://github.com/Availity/availity-react/blob/720859d6e3569d8b5ea5918616bd07a7dfe04a3d/packages/reactstrap-validation-select/AvSelectField.d.ts#L2

**Comment by djejaquino** [comment]
This is probably a long shot but, shouldn't `AvSelectFieldProps` extend `AvSelectField` descendants props interfaces like `AvSelect` or `react-select`'s `AsyncPaginate` and `Select`?

When working with this "ghost" props on Typescript, we run into issues like:
> Property 'components' does not exist on type 'IntrinsicAttributes & AvSelectFieldProps & { children?: ReactNode; }

This is easily overcomable by using spread operator `{...attrs}` on component declaration but it feels like imperative programming and there is no IntelliSense for the props.

IDK, am I being too fussy here?

**Comment by GoPro16** [comment]
You are correct that they should be extending the base `AvSelectProps`. We must have overlooked this in the ts def writes.

And no you are not too fussy lol.

Its hard for us to get these right at the moment since we aren't actively writing any web apps in typescript. With that being said we are functioning in a reactive state when it comes to the typescript definitions whereas we will in the future be starting to write some apps in typescript to assure that our components are functioning correctly and can proactively make sure these definitions are written correctly the first time.

**Comment by GoPro16** [comment]
@djejaquino 
Created another issue: https://github.com/Availity/availity-react/issues/284

Feel free to submit a PR for that

**Comment by djejaquino** [comment]
@GoPro16 Done
