### ISSUE TITLE
Typescript Definitions | Update reactstrap-validation-select to extend base types

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-react#284]
Looking at `@availity/reactstrap-validation-select` we are not properly extending the base `AvSelect` Props in the `AvSelectField` and same for the reosurce select.

However, `@availity/select` is doing this correct so we can checkout how its doing it there and copy the same logic over.

**Comment by djejaquino** [comment]
#285 fixes this

**Comment by djejaquino** [comment]
@GoPro16 does it usually take long for a package to be published on NPM after PR is merged? Anywhere to follow this process?

**Comment by GoPro16** [comment]
I would have to look into a better way for this but I have my notifications enabled on npm so it notifies me when any new package is published from our organization. Its generally within a few minutes of it being merged. `@availity/reactstrap-validation-select` is published out there now.
