### ISSUE TITLE
`Field` label not connected to input

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/availity-react#303]
### Current Behavior

`Field` is not accessible. Clicking the label does not add focus to the input.

### Expected behavior

Clicking the label generated by `Field` should give the input generated by `Field` focus.

### Reproducible example

https://availity.github.io/availity-react/form/components/field/

### Suggested solution(s)

Currently, the label's `for` attribute is set to the input's `name`. This is not how HTML works. The `for` attribute _must_ match the associated input's `id`.
Previously, `AvField` would use the `name` as the `id` if no `id` was provided. I believe a similar solution should be implemented to make the generated IDs more predictable (which is better for e2e testing tools) (or generate and cache uuid to use).

### Additional context

https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-explicitly
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Attributes

### Your environment

Doesn't matter.

**Comment by agawish** [comment]
I can help with that, should be a quick one

**Comment by GoPro16** [comment]
> I can help with that, should be a quick one

Sounds good, if you want to wait until tomorrow you can get PR credit for Hacktoberfest otherwise, go for it man!

**Comment by agawish** [comment]
I will work on it today and will submit it tomorrow, how's that?

**Comment by GoPro16** [comment]
I'm not sure how it all works, but if you make the commit on the day before I am not sure if that PR counts as credit as the changes were made the day before. Just as a precaution if you care haha.

**Comment by agawish** [comment]
I'm wondering if I should update the doc file to reflect the fact that if you use `id` in the field, it will be used as the ID of the input component or not?

**Comment by TheSharpieOne** [comment]
You can start now. It's Oct 1st somewhere in the world so registration is open and they have started tracking PRs.

![image](https://user-images.githubusercontent.com/664714/65905039-c8301900-e38d-11e9-8b6b-2ce8fb7eb66f.png)

**Comment by agawish** [comment]
All done, please review it :)
