### ISSUE TITLE
Date Range does not have presets

### ISSUE THREAD

**Issue by adrian-santos** [Availity/availity-react#331]
### Current Behavior

**DateRange** in component `@availity/form` doesn't have the preset ranges

### Desired Behavior

When adding the ranges in the props, the component should be able to add the ranges button

### Suggested Solution

https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/src/AvDateRange.js#L445

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

Copy **AvDateRange** format

### Additional context

https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/src/AvDateRange.js#L445

**Comment by GoPro16** [comment]
All you have to do is add `ranges` as a `boolean` and all the relative default ranges will be added

[Default Ranges](https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/src/AvDateRange.js#L19-L44)

[Boolean Check](https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/src/AvDateRange.js#L450)

**Comment by TheSharpieOne** [comment]
I think @adrian-santos is asking for that feature to be migrated from `@availity/reactstrap-validation-date`'s `AvDateRange` to `@availity/date`'s `DateRange`

**Comment by GoPro16** [comment]
> I think @adrian-santos is asking for that feature to be migrated from `@availity/reactstrap-validation-date`'s `AvDateRange` to `@availity/date`'s `DateRange`

Read that way too quick 🙃  makes more sense now 🤦‍♂

**Comment by stephanrotolante** [comment]
I got this issue!
![shrek](https://user-images.githubusercontent.com/28844768/66490009-7d458e00-ea7e-11e9-8098-31f15c8eb0f8.jpeg)
