### ISSUE TITLE
Add showClearIcon on Field and SelectField

### ISSUE THREAD

**Issue by adrian-santos** [Availity/availity-react#369]
### Current Behavior

Usage is currently a fire and forget method. There's no way to clear `Select Field` if a form is being reused over and over while the component keeps the current state of the app.

### Desired Behavior

Have a showClearIcon `X` mark on the right side of the field which will clear the current values of a field

![Screen Shot 2019-11-01 at 12 28 52 PM](https://user-images.githubusercontent.com/17089609/68039949-9f0fea80-fca3-11e9-8eae-97933c892e8d.png)

### Suggested Solution

`isMulti` implementation in Select Field

### Who does this impact? Who is this for?
All Users

### Describe alternatives you've considered

Add a clear button at the bottom of the form, but those would involve clearing everything in the form, not individual

**Comment by GoPro16** [comment]
`react-select` already supports this.

[React-Select Props](https://react-select.com/props#select-props)

`isClearable` boolean value.
