### ISSUE TITLE
A way to access Formik children/component props

### ISSUE THREAD

**Issue by djejaquino** [Availity/availity-react#428]
## ❓Question

Is there a way to access Formik [methods/props](https://jaredpalmer.com/formik/docs/api/formik#formik-render-methods-and-props) through `@availity/form`?

Two things to consider:

- The [children](https://github.com/Availity/availity-react/blob/1aaf6f8d87b497f73a1250f0a7c749034170e224/packages/form/src/Form.js#L29) of Availity `Form` are turned into `children` of Reacstrap `Form`; passing a function to it breaks the app and props are not injected (duh);
- Adding a `component` prop to Availity `Form` and passing it to `Formik` makes Reactstrap `Form` obsolete.

**Comment by GoPro16** [comment]
[useFormik](https://jaredpalmer.com/formik/docs/api/useFormik#useformik-values-config-formikconfig-values-formikprops-values) returns the same values that are passed to the render method of the `Formik` Component.

After using this library for some time, I have found it easier for some more complex apps to manually create my `Formik` component and then pass the `handleSubmit` and `handleReset` method to the `RsForm` manually. Some use cases include rendering formik as a HOC so I can have some information or display some other UI before starting the render of the Form that may manipulate the values in some way.

**Comment by djejaquino** [comment]
So `useFormik` would dismiss declaring an Availity `Form` at all or am I missing something?

Maybe that [blog suggestion](https://github.com/Availity/availity-react/issues/359#issuecomment-545485781) would come in handy now

**Comment by GoPro16** [comment]
The below snippet would replace the `Form` component exported from `@availity/form`

```jsx
<Formik>
 <RsForm></RsForm>
</Formik>
```

And yes, would be nice to dedicate more time this year to open source for that 😄

**Comment by djejaquino** [comment]
What about [this](https://github.com/djejaquino/availity-react/blob/88663b4a7d8e15b48272c06cfb81b2ff9e8987cc/packages/form/src/Form.js#L28)? Would that be an acceptable PR? @GoPro16 

Edit: PropTypes would be updated, of course.

**Comment by GoPro16** [comment]
@djejaquino  yes please submit that PR against this repo and I will get that merged!

Sorry for the delay I must have overlooked this.
