### ISSUE TITLE
Airbnb/react-dates shims

### ISSUE THREAD

**Issue by djejaquino** [Availity/availity-react#433]
### Current Behavior

`@avality/react-strap-validation-date` is not working on IE 11 anymore since 3.x.
It throws an `Object doesn't support property or method 'padStart'` error when user clicks on calendar icon.

This happens in fresh started `npx @availity/workflow` apps also.

### Suggested solution(s)

Add airbnb shims on related `@availity` packages. Refs  https://github.com/airbnb/react-dates/issues/1675 https://github.com/airbnb/react-dates/issues/1728

### Workaround

Rollback to 1.x or 2.x

### Your environment

  Binaries:
    Node: 8.9.4 - C:\Program Files\IBM\node\node.EXE
    npm: 5.6.0 - C:\Program Files\IBM\node\npm.CMD

**Comment by GoPro16** [comment]
I don't think we should be adding in their custom polyfills as it just starts to bloat our projects. I am pretty sure though if you are on the latest version of `@availity/workflow` we should have the necessary polyfills for it to work. If not we should add them into workflow.

https://bundlephobia.com/result?p=airbnb-browser-shims@3.3.0
https://bundlephobia.com/result?p=airbnb-js-shims@2.2.1

**Comment by djejaquino** [comment]
My bad, new app using `@availity/workflow@^7.5.0` results into blank screen on IE 11, with error `SCRIPT1010: Expected identifier`, pointing to bundle line: 
```javascript
const { Html5Entities } = __webpack_require__(/*! html-entities */ "../../node_modules/html-entities/index.js");
```

Now for an "old" app, started with:
```
"@availity/workflow": "^6.0.3",
"@availity/workflow-plugin-react": "^6.0.3",
```
Do you suggest just importing their shims to the project?

**Comment by GoPro16** [comment]
I haven't seen that error before. I would be interested to see what is causing that.

If it's an old app, I would suggest upgrading to get the latest workflow changes. There aren't many breaking changes that require an intense amount of refactor from the user.

The only reason we breaking changed workflow a 3 times was it was potentially requiring users to make a change to their `workflow.js` or `package.json` in order to properly work with the lts.

**Comment by djejaquino** [comment]
What can I provide you for investigate that error?

I will upgrade workflow and will let you know how that turns out.

**Comment by djejaquino** [comment]
@GoPro16 I have upgraded `@availity/workflow` to `7.5.3` using `npx @availity/workflow-upgrade` and installing required dependencies. Error persists in IE. What can be done?

**Comment by GoPro16** [comment]
We had begun going down the rabbit whole of seeing exactly what "shims" were missing. One of our devs had added the polyfill for padStart but then following that error being fixed another one came up. It would be nice to find exactly what polyfills needs to be added vs just adding them all in. 

As a temporary solution it would be good to know if we just need the shims from `import 'airbnb-browser-shims/browser-only';` vs also from the `es2015` ones. if that was the case we could look into adding that package as a dependency to `@availity/date` and only call it if the methods don't exist in that browser, in this case IE

**Comment by jordan-a-young** [comment]
I was having issues with the datepicker in IE as well when running `@availity/workflow`. I use `core-js` for my polyfills. I added `import 'corejs/stable'` to get things working. I know this is not optimal, but it gets things working until we locate what polyfills are required.

**Comment by djejaquino** [comment]
@GoPro16 up until now, `string.prototype.padstart` alone has did the trick

**Comment by GoPro16** [comment]
I don't see why we can't include that polyfill alone then inside of this package.

**Comment by djejaquino** [comment]
Please consider both `@availity\reactstrap-validation-date` and `@availity\date` and don't forget `shim()` call or set it up under Webpack

**Comment by GoPro16** [comment]
Since its a bug fix we will still include for both

**Comment by djejaquino** [comment]
Cool. 
Closing this for now. Will reopen in case of other missing polyfills.

**Comment by GoPro16** [comment]
I'm going to keep this open actually until we have either fixed it in this package or in `@availity/workflow`

**Comment by djejaquino** [comment]
@GoPro16 after upgrading `workflow` I ran into this issue during `npm run staging`

```
ERROR in ./index.js
Module build failed (from C:/Users/DOA3960/Documents/Projects/humana-epaf-new/node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\DOA3960\Documents\Projects\humana-epaf-new\project\app\index.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "staging".
```

Did I miss some step in the migration?

**Comment by GoPro16** [comment]
The script for `staging` should be:

```
cross-env NODE_ENV=staging av release
```

https://github.com/Availity/availity-starter-typescript/blob/master/package.json#L24

**Comment by djejaquino** [comment]
Sorry, I pasted more than I should.  This is the issue:

```
ERROR in ./index.js
Module build failed (from C:/Users/DOA3960/Documents/Projects/humana-epaf-new/node_modules/babel-loader/lib/index.js):
Error: [BABEL] ...\project\app\index.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "staging".
```

`staging` script is the same.

**Comment by djejaquino** [comment]
Sorry, I pasted more than I should. This is the issue:
```
ERROR in ./index.js
Module build failed (from .../node_modules/babel-loader/lib/index.js):
Error: [BABEL] ...\project\app\index.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "staging".
```

staging script is the same.

**Comment by GoPro16** [comment]
Seems like this a new issue introduced with the `babel-preset-react-app` when we added it to workflow. `npm run production` should work for now. I will open up a bug report in that repo

**Comment by GoPro16** [comment]
https://github.com/Availity/availity-workflow/issues/391

**Comment by djejaquino** [comment]
`production` won't include sourcemaps while `staging` does, is that correct?

**Comment by GoPro16** [comment]
i don't think we create the `source-maps` but really the main thing is that we don't minify the code at all. So its still readable to the point where you know where and what to make changes to in the browser to test a change out.

**Comment by djejaquino** [comment]
@GoPro16 About that IE issue with fresh started projects, do you want me to open an issue on `@availity/workflow` or is it already under investigation?

https://github.com/Availity/availity-react/issues/433#issuecomment-580776184

**Comment by GoPro16** [comment]
I am not entirely sure where the scope is going to lye at but I'm going to be looking into it here soon.

I will use this issue to update if there is anything and if it ends up requiring a workflow PR I will just cross reference this issue in there.

**Comment by djejaquino** [comment]
@GoPro16 another problem we are facing with `react-dates` is [this issue](https://github.com/airbnb/react-dates/issues/1714) that is resulting into the following:

![image](https://user-images.githubusercontent.com/5549408/73782315-aba75180-4770-11ea-8101-c9d9e02f87c6.png)
(hidden some app content)

Is there anything that can be done from `@availity/reactstrap-validation-date` perspective?

**Comment by GoPro16** [comment]
That looks wild haha. What does your code snippet look like? That seems like an edge case if no one else has reported that in `react-dates`

**Comment by djejaquino** [comment]
This should suffice:
```jsx
<AvForm>
    <AvDateField id="dosFrom" name="dosFrom" label="Date of Service"
       validate={{
        min: { value: moment().startOf('year'), errorMessage: "Start Date must be in current calendar year" },
        max: { value: moment().endOf('month'), errorMessage: "Start Date can't be in future month" }}}/>
  </AvForm>
```
Sometimes disabled dates don't have adequate css classes, and yet sometimes classes are added when you hover them.

P.S.: don't mind the test error messages

**Comment by GoPro16** [comment]
Their package have gotten so huge that is so difficult to follow all of what is happening in there. I am not sure how much it would help but maybe we remove the `initialize` logic from the package itself and force the person implementing it to call it inside of their app.

Not sure if this would make a difference but potentially would since the `initialize` would only be called once in the project whereas in here its called multiple times depending on how many times the import is used across the app.

[Source](https://github.com/Availity/availity-react/blob/master/packages/date/src/Date.js#L5)

Alternatively, we could just remove the date picker all together and go back to using the html fields for dates. The more time we have invested into trying to get a solid date picker the more I wish we just stuck to the bare bones unless there really was one that would work 100% of the time. ( This would make a lot of people upset thou 🙃 )

**Comment by djejaquino** [comment]
@GoPro16 I am down for any implementation that gives me pretty red validation messages and grays out invalid dates from calendar.

Should we expect any updates on `@availity\reactstrap-validation-date` soon?

**Comment by GoPro16** [comment]
I have to try to replicate that css issue first before I can take a look. Going to get a codesandbox up hopefully today to get it replicated or if you can that would be great. From there we can look at making change to fix this. However, it sounds like an issue with `react-dates` and not our lib unless you are speaking about the shims which hasn't been started yet.

**Comment by djejaquino** [comment]
Not really worried about shims, since we added it to our project. But the styling issue with `react-dates`, you mentioned something about `initialize` logic changes. I would call that priority to us, along with fresh `workflow` projects not running in IE.

**Comment by GoPro16** [comment]
For some reason I can't get this to replicate in [codesandbox](https://codesandbox.io/s/react-dates-issue-9mxyp). However I also had to import the `_datepicker.css` from `react-dates` for it to register in codesandbox.

I think we should only be importing that file once and before the overrides file from `@availity/date`. I'm curious now if you have other datepickers on the same page of your app you discovered this on?

**Comment by djejaquino** [comment]
@GoPro16 were you able to load that codesandbox on IE?

**Comment by GoPro16** [comment]
No codesandbox and stackblitz both don't work in IE 😦

**Comment by djejaquino** [comment]
Well, the issue is IE only. If you can bootstrap an `availity-workflow` project and use [this](https://github.com/Availity/availity-react/issues/433#issuecomment-582108142) snippet, run in IE, I am 98.9% sure you will be able to reproduce it.

**Comment by GoPro16** [comment]
I added the `shim` for `padStart` which is why I closed the issue. If you are talking about the IE issue with the style overrides we can maybe track that on a different issue and can make some comments in the `react-dates` issue list about it.

Also would be interested to know how you calculated 98.9% 😆
