### ISSUE TITLE
Module parse failed (Failed to compile)

### ISSUE THREAD

**Issue by fetahokey** [Availity/availity-react#444]
## ❓failed to compile my react project after installing @availity/upload !

Message error: 
**You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file**
webpack.json: 

> `  ],
>     module: {
>         rules: [
>             {
>                 test: /\.js$/,
>                 exclude: /node_modules/,
>                 use: 'babel-loader'
>             },`

**Comment by GoPro16** [comment]
Duplicate of #22
