### ISSUE TITLE
Gatsby Docs | unnecessary semi-colon being added from vscode

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-react#476]
### Current Behavior

If a user that is using `vscode` has the `vscode-prettier` extension installed and runs the autoformatter on `markdown` files with `jsx` codeblocks, the formatter will add a trailing semi colon after the closing jsx tag.

[Example Diff](https://github.com/Availity/availity-react/commit/3a5da04915b424df15227b520959c3996b425e71#diff-426cb8d56a1e54677c1ef80b1234a35aL18)

### Expected behavior

The formatter should ignore adding the semi-colon after the jsx tag as its not written in the same form that a normal react component file would look like.

### Reproducible example

1. Open vscode
2. Install [vscode-prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and enable auto formatting
3. Open any markdown file with `jsx` codeblocks
4. Save the file and you will see a diff of where it inserts the trailing semi-colon

### Suggested solution(s)

Look into adding custom settings to the `prettier` config in the root `package.json` to override this default behavior.

**Comment by jordan-a-young** [comment]
Closing since we do not use Gatsby for our docs anymore
