### ISSUE TITLE
autoSync in DateRangeField causes browser window to lock up

### ISSUE THREAD

**Issue by Valar05** [Availity/availity-react#483]
Steps to reproduce:

1. Navigate to docs: https://availity.github.io/availity-react/form/date/components/date-range-field/
2. Add autoSync prop to the DateRangeField
3. Select both dates in the calendar picker - the calendar will close.  This bug will occur when clicking both dates, or when typing both dates - but it will only occur after the calendar has closed.
4. Re-open the calendar with the calendar icon button (bug does not happen when clicking the input fields)
5. Wait several minutes to kill the tab as the entire page ceases to function.

I've replicated this in both chrome and firefox, and I'm going to attempt to fork the repo and fix it.

**Comment by chrishavekost** [comment]
It seems like the logic inside `onFocusChange` isn't entirely correct. It's causing an infinite loop where `syncDates` is constantly being called with the `input` alternating between `startDate` and `endDate`. 

Changing `if (autoSync) await syncDates();` to something like `if (!input && autoSync) await syncDates();` should fix this.
