### ISSUE TITLE
Attempt to use the AvOrganizationSelect component

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#491]
## ❓Question

I'm trying to use the `AvOrganizationSelect` component, and getting the current error in my console 
``` 
Uncaught TypeError: Cannot read property 'defaultConfig' of undefined
    at Function.../../node_modules/@availity/reactstrap-validation-select/AvResourceSelect.js.AvResourceSelect.create (AvResourceSelect.js:220)
```

```
<AvOrganizationSelect
     name="organizations"
     id="organizations"
     onChange={this.onSelectedOrganization}
     errorMessage="Please select an organization"
     placeholder="Select an Organization"
     required
/>
```

What am i missing? I couldn't find a good example in the tests

**Comment by GoPro16** [comment]
Hey! This is an issue with out of date `@availity/api-core` and/or `@availity/api-axios` dependencies. Just update those to the latest and it will fix it.

**Comment by diegodesouza** [comment]
@GoPro16 Will look into that. Thanks

**Comment by diegodesouza** [comment]
That was it, @GoPro16 thanks again
