### ISSUE TITLE
AvSelectField shows warning in console.

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#504]
### Current Behavior

When entering any alphanumeric that does not match a date in the input and click away, I see the following warning:

`Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.`

No matter what I did i wasn't able to remove it. 

### Expected behavior

Not see the warning above.

### Reproducible example

https://stackblitz.com/edit/react-afkpmo

**Comment by TheSharpieOne** [comment]
Probably b/c `getDateValue` returns `null` if the date is invalid: https://github.com/Availity/availity-react/blob/51bc49a58e9704f4085b79c73cd8d3e143fd3f36/packages/reactstrap-validation-date/src/AvDate.js#L27-L36
Maybe it should return an empty string?

**Comment by diegodesouza** [comment]
@TheSharpieOne  Unfortunately when returning a string renders this 
```
Warning: Failed prop type: Invalid input type: `date` of type `string` supplied to `withStyles(SingleDatePicker)`, expected `object`.
```

**Comment by GoPro16** [comment]
This is a known issue with `react-dates`: https://github.com/airbnb/react-dates/issues/950

Seems to be related to react-hot-loader which we use. However if you enable the experimental hot loader I am curious if you still get this error:

```js
config.development.hotLoader = {
  enabled: true,
  experimental: true
}
```

Make sure you are on the latest version of workflow
