### ISSUE TITLE
Masking numbers like Date, Currency, Phone Number as an optional prop

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#524]
### Current Behavior

For a telephone masking I was able to use https://github.com/sanniassin/react-input-mask, while attempting to implement the same for for date, some errors prevented it from working properly. 

### Desired Behavior

Option for masking the numbers like phone number, currency, date.

**Comment by diegodesouza** [comment]
Please let me know if this is possible.

**Comment by GoPro16** [comment]
When it comes to dates I think input masking gets pretty complex for those field types.

What I would recommend doing is just using the `@availity/date` component and passing the neccessary `react-dates` props for the calendar icon to not show up so that you have input masking that it provides.

**Comment by GoPro16** [comment]
Sorry, it doesn't input mask but it does autocomplete if its a valid date from any of the formats.

**Comment by diegodesouza** [comment]
That's fair. @GoPro16 as far as masking date. One of the challenges we're facing right now is trying to use some other library along with `AvField` for masking currencies.

**Comment by diegodesouza** [comment]
So I suggested the masking for "any" type of number per se

**Comment by GoPro16** [comment]
Hmmm, okay we can certainly work towards maybe a codesandbox solution first and see how that floats. But I think we have traditionally tried to stay away from input masking as it potentially becomes a 508 issue where we are reformatting the input as the user is typing, which again is awesome but doesn't necessarily work for 100% of users. 

I will see what I can cook up on codesandbox rq and post here.

**Comment by GoPro16** [comment]
https://codesandbox.io/s/currency-formik-uij3r?file=/src/Currency.js

You probably get the idea but, again we don't recommend input masking and the preferred approach is to handle the formatting on blur to prevent the user from being interrupted.

**Comment by diegodesouza** [comment]
Gotcha, I don't know what the implications would be from an accessibility stand point.
