### ISSUE TITLE
reactstrap-validation-select | Keep Selected Value

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#528]
## ❓Question

Is there a way to keep the selected value for AvOrganization after coming back from another page?

**Comment by diegodesouza** [comment]
The idea is: 
i select an org, move forward to a different page, and then use react router to go back. Having the previous selected value in place. I have tried the `value` prop, but that has a funky behavior.

**Comment by diegodesouza** [comment]
@GoPro16 do you have an input?

**Comment by GoPro16** [comment]
Hey @diegodesouza! Are you using `@availity/form` or `@availity/reactstrap-validation-select` for these?

Since the `ResourceSelect` is using the [raw prop](https://availity.github.io/availity-react/form/select/components/select/#raw-boolean) then the value is actually an object. You cannot pass `value` props to the selects as we want this to be managed all through formik but there is an open issue to address passing value props down.

https://codesandbox.io/s/select-prefill-c5b0x?file=/src/App.js

**Comment by diegodesouza** [comment]
@GoPro16 we're using `import {AvOrganizationSelect} from '@availity/reactstrap-validation-select/resources'`

**Comment by diegodesouza** [comment]
I tried, passing an object to the `value` as well, didn't work =/

**Comment by diegodesouza** [comment]
and this form `import {AvForm} from 'availity-reactstrap-validation';`

**Comment by GoPro16** [comment]
Hmmmm, I just modified the above codesandbox and got it working with `SelectField`. I can hook it up to a ResourceSelect if needed. You want to post a code snippet of what all the current props you are passing look like?

**Comment by diegodesouza** [comment]
sure

Welcome.js
```
 render() {
    return (
      <AvForm onValidSubmit={this.createNewInquiry}>
        <Card>
          <CardBody>
            <Message messageStore={messageStore}/>
            <Organization />
            <Row className='mt-4'>
              <Col sm='4'>
                <strong>I want to:</strong>
              </Col>
            </Row>
            <Row>
              <Col sm="3">
                <div className="form-controls form-controls-card">
                  <Button type="submit" color="primary">Create New Inquiry</Button>
                </div>
              </Col>
              <Col sm="3">
                <div className="form-controls form-controls-card">
                  <Button type="button" color="primary" onClick={this.viewInquiries}>View Inquiries</Button>
                </div>
              </Col>
            </Row>
          </CardBody>
        </Card>
      </AvForm>
    );
  }
```

organization.js

```
 <AvOrganizationSelect
                  id="organization"
                  name="organization"
                  label="Organization*"
                  value={{value: selectedOrganizationId, label: selectedOrganizationName}}
                  options={organizations.map(org => ({value: org.id, label: org.name, key: org.id + org.name}))}
                  onChange={this.onSelectedOrganization}
                  required
                  placeholder="Please select an organization"
                  validate={{
                    required: {
                      value: true,
                      errorMessage: 'Please select an Organization.'
                    }
                  }}
              />
```

**Comment by diegodesouza** [comment]
it seems strange to me that for `AvOrganizationSelect` one of our team members is doing the `options` manually

**Comment by diegodesouza** [comment]
with that, the input looks empty, like the `placeholder` doesn't show, and i have to click on the option a couple of times for it to take effect, then it disappears again

**Comment by GoPro16** [comment]
Hmmm yeah, if you are manually populating the `options` prop then I am not sure why you need that component in the first place. You should just use `AvSelectField` at that point like I show in the codsandbox

**Comment by diegodesouza** [comment]
let me try that

**Comment by diegodesouza** [comment]
https://codesandbox.io/s/select-prefill-9c6ty?file=/src/App.js

**Comment by diegodesouza** [comment]
so that's what's been happening. The thing is I don't know what value is going to be selected, so that value needs to be 'dynamic'

**Comment by GoPro16** [comment]
Maybe this will help answer your issue: https://codesandbox.io/s/select-prefill-llod3?file=/src/App.js

You pass the whole `value` object as either `undefined` or the value. Given the reason it is this was is because we have the `raw` prop which means that we are expecting the whole object as the value and not a property from one of the options.

What you can do if you want to just have the `id` as the value is something like the below:

```jsx
const values = {
  organization: undefined
};

const onChange = value => {
  values.organization = value;
};

export default () => (
  <Container>
    <AvForm>
      <AvSelectField
        name="selectField"
        label="Select Field"
        labelKey="label"
        valueKey="value"
        onChange={onChange}
        options={[
          {
            label: "0",
            value: "0"
          },
          {
            label: "1",
            value: "1"
          }
        ]}
        value={values.organization}
      />
      <Button type="submit" color="primary">
        Submit
      </Button>
    </AvForm>
  </Container>
);
```

**Comment by diegodesouza** [comment]
It sill doesn't work for me. @GoPro16, when coming back to the page, the value is gone

**Comment by diegodesouza** [comment]
so I have tried the `history.goBack()` as well `history.push(\)` method.

**Comment by diegodesouza** [comment]
strangely it's working for another component but not the example i shared. (ノಠ益ಠ)ノ彡┻━┻

**Comment by diegodesouza** [comment]
closing it, had to set it in my store. working now. Thank you so much @GoPro16, I appreciate your help

**Comment by GoPro16** [comment]
LOL no problem! 😆
