### ISSUE TITLE
AvSelectField - onChange get the event instead of the value

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#530]
## ❓Question

I'm using the `AvSelectField` and on my `onChange` I'd like to get the event instead of the actual value selected. 

I've tried below and without passing anything to the callback func.
 
```
              <AvSelectField
                id="reason"
                label="Reason*"
                name="reason"
                onChange={(event) => onSelectReason(event)}
                options={
                  getReasonValues().map(reason => ({
                    value: reason.id,
                    label: reason.label,
                    key: reason.code + reason.description
                  }))
                }
                placeholder="Select a Reason"
                required
                validate={{
                  required: {
                    value: true,
                    errorMessage: 'Please select a Reason.'
                  },
                }}
                value={reason}
              />
```

is there a way for me to get the full event instead?

**Comment by GoPro16** [comment]
It doesn't seem like `react-select` does this however it does look like the second param in their [onChange](https://react-select.com/props) function is the action that was performed if its enough we can also provide that in our onChange callback

**Comment by diegodesouza** [comment]
we can try that @GoPro16

**Comment by diegodesouza** [comment]
I have a few instances where the value passed to the backend is different than the value to be displayed to the user

**Comment by diegodesouza** [comment]
Do we have an ETA on it? also

**Comment by GoPro16** [comment]
In your case I don't think this will end up helping you because the `action` will always be `select-option` and not anything like `create` or the other `action` strings that are available in `react-select`

```typescript
function(
Oneof<
Object,
Array<Object>,
null,
undefined
>,
{
action required Oneof<
"select-option",
"deselect-option",
"remove-value",
"pop-value",
"set-value",
"clear",
"create-option"
>
}
) => undefined
```

**Comment by diegodesouza** [comment]
lets say 

```
options = [
 {
    value: '1',
    label: 'One'
 },
 { 
    value: '2',
    label: 'Two'
  }
]

```

if the selection-option gives me the label and not the value, the this should help, as long as I can get both on selection. @GoPro16

**Comment by GoPro16** [comment]
No the action is just a enum of different actions that were taking which would be the value `select-option` not the label or value of the option.

**Comment by diegodesouza** [comment]
@GoPro16 any suggestion on what we could do then?

**Comment by GoPro16** [comment]
I’m not quite following what the use case is if you want to explain that I can help

**Comment by nylon22** [comment]
would the `raw` prop be useful here? https://availity.github.io/availity-react/form/select/components/select/#raw-boolean

**Comment by diegodesouza** [comment]
@nylon22 thank you! raw works for me

**Comment by diegodesouza** [comment]
@nylon22 strange thing is when using the `raw` prop, i have to click twice for the value be selected/reflect the change.

**Comment by GoPro16** [comment]
Where is your `value` prop coming from and if its a mobx store make sure you wrapped your component in observer. It may be lost in a state update potentially.

**Comment by diegodesouza** [comment]
@GoPro16 

```
mobx store
...
@observable medicalRecordType = '';
...

component is wrapped in @observer
value={medicalRecordType}

**Comment by GoPro16** [comment]
I would try to make a code sandbox to replicate. Unfortunately I cannot reproduce this locally so I am sure it’s has to do something with the lifecycle/state observers

**Comment by diegodesouza** [comment]
@GoPro16 https://stackblitz.com/edit/react-availity-testing please check this. thanks

**Comment by GoPro16** [comment]
https://stackblitz.com/edit/react-availity-testing-zmvq9j?file=create.js

The main problem was you were exporting a new instance of the mobx store everytime which reset the value. Also you should not map over an array to make it fit the select vs just modifying the label/value keys to match what the object is already expecting

**Comment by diegodesouza** [comment]
Hmm, interesting, will update my code and let you know. Thanks @GoPro16

**Comment by diegodesouza** [comment]
@GoPro16 if you console.log the `setMedicalRecord` you'll see we only get the label back now.

**Comment by GoPro16** [comment]
If you add the raw prop back it will return everything.

**Comment by diegodesouza** [comment]
`raw` is there @GoPro16

**Comment by GoPro16** [comment]
I just modified my stackblitz fork to remove some of the args in favor of the single for the whole object. It seems to be working for me.

```
  onChange = rawValue => {
    console.log("rawValue",rawValue)
    const { setMedicalRecordType } = Store;
    setMedicalRecordType(rawValue);
  };
```

**Comment by GoPro16** [comment]
This seems to be a user error, locking this as its unrelated to OSS questions and more so impl. We can continue this on gitlab if needed.
