### ISSUE TITLE
Return entire object when set defaultValue

### ISSUE THREAD

**Issue by nguyenhoavuong** [Availity/availity-react#542]
### Version 5.2.0

I had set some pros for AvSelectField like this:  
<AvSelectField name="brandId" raw = false, defaultValue={value: 1, label: "A"} ... />
and put it in get it in AvForm, when submit form **onSubmit** function of **AvForm** like this:
onSubmit = (event, errors, values) = {
    ....
}
I think in normal case values.brandId should be **1** but it was **{value: 1, label: "A"}** (entire object of the selected value instead)

Is that bug?

Note: If **change defaultValue** after init component,  values.brandId in form contains **only value key**

**Comment by diegodesouza** [comment]
@nguyenhoavuong I've had an instance where i needed the whole object back also. The `raw` prop helped me get it. I haven't used the `defaultValue` before, i use `value` and instantiate the `"defaultValue"` meaning `value` like that.

**Comment by nguyenhoavuong** [comment]
> @nguyenhoavuong I've had an instance where i needed the whole object back also. The `raw` prop helped me get it. I haven't used the `defaultValue` before, i use `value` and instantiate the **`"defaultValue"` meaning `value` like that**.

Yep, i know it and already trying before open this issue, but **using 'value' instead of 'defaultValue'** still got the same result

**Comment by nylon22** [comment]
I recommend looking into the `valueKey` prop. See here: https://availity.github.io/availity-react/form/select/components/select/#valuekey-string 

If that doesn't work, please provide a stackblitz to help recreate the issue

**Comment by nguyenhoavuong** [comment]
> I recommend looking into the `valueKey` prop. See here: https://availity.github.io/availity-react/form/select/components/select/#valuekey-string
> 
> If that doesn't work, please provide a stackblitz to help recreate the issue



> I recommend looking into the `valueKey` prop. See here: https://availity.github.io/availity-react/form/select/components/select/#valuekey-string
> 
> If that doesn't work, please provide a stackblitz to help recreate the issue

Dont know if it's work but i have already solved issue while wating for response, thanks all for help
