### ISSUE TITLE
availity pagination - items warning

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#543]
## ❓Question

So i'm passing down an `observableArray` to `items` like so
<img width="802" alt="Screen Shot 2020-05-11 at 10 47 01 AM" src="https://user-images.githubusercontent.com/7575914/81575708-55503d00-9375-11ea-8bed-d73a6eaa4af9.png">
but am getting this warning, 
<img width="963" alt="Screen Shot 2020-05-11 at 10 51 48 AM" src="https://user-images.githubusercontent.com/7575914/81575835-7c0e7380-9375-11ea-8c46-5aa10e225408.png">
The prop definition from the docs

![Screen Shot 2020-05-11 at 10 52 56 AM](https://user-images.githubusercontent.com/7575914/81575942-9fd1b980-9375-11ea-9ef6-f7129def7bb3.png)
says `array of objects` wondering if `observable` behaves differently? if so what solution would you suggest?

**Comment by nylon22** [comment]
pass down `inquiries.slice()`.

```
const observableArray = mobx.observable([]);
console.log(Array.isArray(observableArray)); // prints false
console.log(Array.isArray(observableArray.slice())); // prints true
```
