### ISSUE TITLE
Availity Upload - validate on click

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#544]
## ❓Question

I'm wondering if there's a way to validate other inputs when i click the `+Add File` button. For example in our implementation we have a `select` field for a "Document Type" and this is a required field. But since there's no validation in the Upload component the user can click and upload files without ever touching the select field. 
Here's a screenshot of what that looks like. 

![Screen Shot 2020-05-13 at 12 58 51 PM](https://user-images.githubusercontent.com/7575914/81842329-d7796680-9519-11ea-87b6-8d99f986ebc4.png)

thanks in advance

**Comment by nylon22** [comment]
@diegodesouza you could use the `disabled` prop to disable the `Add File` button if the select is invalid

**Comment by diegodesouza** [comment]
Excellent, that worked for us. Thanks @nylon22
