### ISSUE TITLE
Pagination - get total count per page

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#546]
## ❓Question

Is there a way to get the total count shown on the current page. 
In the example below I'd like to show `Showing 3 Inquiries of 10 Inquiries` and on last page `Showing 1 Inquiries of 10 Inquiries`?
![Screen Shot 2020-05-18 at 3 59 35 PM](https://user-images.githubusercontent.com/7575914/82254295-97065800-9920-11ea-8ffa-82255a0e2b93.png)

**Comment by nylon22** [comment]
@diegodesouza You can get this information from `page` in the `usePagination` hook.

**Comment by diegodesouza** [comment]
@nylon22 thank you, i should have been more specific, We're using a class component. 

```
import React from 'react';
import { PaginationContext } from '@availity/pagination';
// ...
class PageSetter extends React.Component {
  render() {
    const { page, setPage } = this.context;
    return (
      <input
        type="text"
        value={page}
        onChange={({ target }) => setPage(target.value)}
      />
    );
  }
}
PageSetter.contextType = PaginationContext;
```

this is what i see in the documentation [here](https://availity.github.io/availity-react/components/pagination/context/)

I have tried both `PaginationContext` or `this.context` though i know i don't have any context defined in my component.

`const {page} = PaginationContext;` // page is undefined

<img width="452" alt="Screen Shot 2020-05-19 at 10 06 05 AM" src="https://user-images.githubusercontent.com/7575914/82336292-607c1c00-99b8-11ea-8b24-41e3dbc121a9.png">

**Comment by nylon22** [comment]
Please see this code sandbox for how to work with context in class components: https://codesandbox.io/s/select-prefill-3r4io?file=/src/App.js

**Comment by diegodesouza** [comment]
Ah my issue was that i was trying to get the context from the parent form. my fault. Thanks @nylon22
