### ISSUE TITLE
Pagination - Always show the controls

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#547]
## ❓Question

I'm wondering if there's a prop or something i can use to always show the pagination controls even though it doesn't match the minimal amount of items required? so for example; if i have the `itemPerPage` set to 10, but only have 9 items, the pagination controls is hidden, whereas we need it to be shown at all times.

**Comment by GoPro16** [comment]
https://availity.github.io/availity-react/components/pagination/controls/#autohide-boolean

Just set `autoHide` to `false` in the props

**Comment by diegodesouza** [comment]
@GoPro16 agh i must be really tired, not sure how missed that. Thanks man
