### ISSUE TITLE
Integration with create-react-app 3.4.1 is not working.

### ISSUE THREAD

**Issue by khenlevy** [Availity/availity-react#603]
### Current Behavior
the package uses stage-3 features without babel at all.
not dist provided (babelified ).

<img width="1035" alt="Screen Shot 2020-08-30 at 1 19 33" src="https://user-images.githubusercontent.com/12776928/91647059-dfc0c780-ea5e-11ea-83cf-e029a7ab6b4c.png">

### Reproducible example
1. create a simple create-react-app
2. past the example of reactstrap-validation-date or reactstrap-validation-select.
3. run, error dislayed.

### Suggested solution(s)
Create dist/build folder or not to use stage-3 without babel.

**Comment by nylon22** [comment]
These packages need babel to be transpiled. We do not distribute them transpiled. You can read more here: https://github.com/Availity/availity-react/issues/22#issuecomment-405969709
