### ISSUE TITLE
AvDateRange range enhancement ideas

### ISSUE THREAD

**Issue by KaseyPowers** [Availity/availity-react#62]
- Especially with the built in ranges, maybe we should try filtering out the ranges that would automatically fail validation? 
ex. `Last Month` and greater shouldn't be shown if max distance is 5 days. 

- Some way to modify/add to the built in ranges (ex. adding `today` or removing just 'Last 120 days')

**Comment by GoPro16** [comment]
I know its not accessible but for some apps that are currently wanting to just show the date picker and not the fields.

**Comment by adrian-santos** [comment]
How about if we add an option for the `rendered month/s` count?

**Comment by GoPro16** [comment]
We should probably close this issue as we shouldn't look into adding new options until we have a new accessible date picker picked out and replaced.

**Comment by GoPro16** [comment]
Closing as we moved to new `react-dates` lib.
