### ISSUE TITLE
Pagination - "Infinite Scroll" happening after clicking pagination controls

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#661]
I wanted to run by you guys an issue I'm having with the pagination component. When I click on the pagination controls instead of it showing a different page, it shows it as if it was an infinite scroll, as i keep "paginating" it adds to the same "page"/list. I checked and it's not adding the new items in the `providers` observable. 

```
  constructor(props) {
    super(props);

    const {commonStore, dashboardStore} = props;

    const {getDashboard, handleChange} = dashboardStore;

    getDashboard()
      .then(response => {
        if(response && response.data && response.data.length > 0) {
          handleChange('providers', response.data) << get the providers here. 
        }
        return null;
      })
      .catch(error => {
        throw new Error(error);
      })
      .finally(() => {
        setBlocking(false);
      })
  }

          <Pagination itemsPerPage={10} items={providers.slice()} defaultPage={1}>
            <Pagination.Controls
              autoHide
              className="top-controls"
              directionLinks
              marginPages={1}
              pageRange={4}
            />
            <Pagination.Content
              className="pagination-content"
              component={Card}
              itemKey="submittedDate"
              downloadFeeSchedule={this.downloadFeeSchedule}
              deleteFeeSchedule={this.deleteFeeSchedule}
            />
            <Pagination.Controls
              autoHide
              className="bottom-controls"
              pageRange={4}
              marginPages={1}
              directionLinks
            />
          </Pagination>

```

**Comment by diegodesouza** [comment]
I noticed also that if i change the `itemsPerPage` to say 2, the issue is resolved.

**Comment by diegodesouza** [comment]
When setting it to 5, and clicking on page 2, i get the infinite scroll behavior, but not page number 3 or larger.

**Comment by diegodesouza** [comment]
Tested with a different set of data. Turns out the data I'm testing this with, has the same `itemKey` for each item. Perhaps this could be added to a `Gotcha` section in the readme. Closing.

**Comment by nylon22** [comment]
@diegodesouza You should've received a duplicate keys warning in your console:

https://github.com/Availity/availity-react/blob/351f9f4a893767e16a28069627a6e424e9be27fd/packages/pagination/src/PaginationContent.js#L83

**Comment by diegodesouza** [comment]
@nylon22 i did, but didn't really think that would cause this kind of issue.

**Comment by diegodesouza** [comment]
I wonder is there's a way to construct the itemKey to be more than one property? as of now i don't know if the property i have available will be unique

**Comment by nylon22** [comment]
@diegodesouza you could iterate through the collection and add a new property to each item that is a combination of two or more fields to make a unique key and then use that as the `itemKey`

**Comment by nylon22** [comment]
@diegodesouza you also may want to consider using `<AvResourcePagination />` to simplify your code a bit.
