### ISSUE TITLE
creatable is not working when using async select

### ISSUE THREAD

**Issue by khenlevy** [Availity/availity-react#664]
both AvSelectField and AvResourceSelect are not working when i am sending creatable prop as true.
passing a function names getResult which returns a promise does works in terms of async select but sending createable has no effect on noResult "mode".
Tried AvResourceSelect also, using either resource={ getResult: myAsyncFn } and just by passing getResult={myAsyncFn}.

Can anyone have a look?

**Comment by nylon22** [comment]
@khenlevy can you share some sample code?
