### ISSUE TITLE
Docs mention Custom resources that dont actually exist

### ISSUE THREAD

**Issue by bryanmorganoverbey** [Availity/availity-react#667]
## 📖 Documentation

I'm looking at: https://availity.github.io/availity-react/form/select/components/resource-select/

which talks about the existence of pre-made resource selects:
AvProviderSelect
AvOrganizationSelect
AvPermissionSelect
AvNavigationSelect
AvUserSelect
AvCodeSelect

But looking in the custom resources folder:
https://github.com/Availity/availity-react/tree/master/packages/select/custom-resources

we only have two of them:
AvOrganizationSelect and AvRegionSelect. 

I could be wrong, and they exist elsewhere, but if we are in agreement that the others don't exist, I'd like to remove these from the docs.

**Comment by nylon22** [comment]
The others do exist. They're just defined here: https://github.com/Availity/availity-react/blob/master/packages/select/resources.js

**Comment by bryanmorganoverbey** [comment]
Sorry, just realized that. Closing
