### ISSUE TITLE
data-testid in production

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/availity-react#68]
https://twitter.com/dan_abramov/status/935661594729746434
> Add your own attributes? data-testid="...". Can then write a Babel plugin to strip them from production bundles.

Recommend using babel-plugin-jsx-remove-data-test-id or something similar to strip out the unneeded attributes from production code.

Maybe workflow should include this by default (maybe an issue should be opened there as well) but for others which just use these components outside of workflow, a note in the readme would be nice.

**Comment by GoPro16** [comment]
Yeah I do like this a lot. The only downside is I am pretty sure since we are not compiling our components in here that `data-testid` will still be carried over unless people using this lib include the babel plugin as well.

I will definitely add this plugin to `@availity/workflow`.

**Comment by TheSharpieOne** [comment]
Yeah, that's why it would only be a note in the readme here.

**Comment by GoPro16** [comment]
Closed via [#326](https://github.com/Availity/availity-workflow/pull/326)
