### ISSUE TITLE
Select - Weird behavior with multi select. 

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#683]
### Current Behavior

https://github.com/Availity/availity-react/issues/662
We have an example where we need to do a multi select search. The options are populated correctly, the issue is when i do the multi select. I'm able to select one and then everything disappears except one other value.

### Reproducible example

https://stackblitz.com/edit/react-ffq5ez?

**Comment by diegodesouza** [comment]
I have tried changing the `buildNetworkOptions` to a computed value and reading the results from a an API call instead. Same behavior

**Comment by nylon22** [comment]
In the example, the `contractCode` is being used as the `value` of the select option, but those contract codes are not unique. The `value` needs to be unique

**Comment by diegodesouza** [comment]
Oddly enough when i add `valueKey`="contratId" which is not part of the object, it works. as expected

**Comment by diegodesouza** [comment]
I don't know if this is possible, but we wanted to have a divider or change the way the options look atleast, like they accomplish in https://reactstrap.github.io/components/dropdowns/ with the `divider`, is this something select provides us with?

**Comment by chrishavekost** [comment]
@diegodesouza It sounds like `react-select`'s [grouped options](https://react-select.com/home#getting-started) are what you're looking for. Our `@availity/select` components should already support grouped options like this in single and multi select situations

https://stackblitz.com/edit/react-mougru?file=store.js

**Comment by nylon22** [comment]
@diegodesouza Here is the link to rendering custom components: https://react-select.com/components

I'm closing this issue as the last question is outside the scope of this repo.

**Comment by diegodesouza** [comment]
@nylon22 sure, thank you, @chrishavekost that gave me a good push towards a solution for us. Thanks
