### ISSUE TITLE
Pagination - PaginationContent doesn't always update after items props change

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#694]
### Current Behavior

PaginationContent doesn't update after `items` props update. 

### Expected behavior

`PaginationContent` update the changes.

### Reproducible example

most of my code is in here, but the stackblitz is failing. It keeps asking me to install `nano-css` after it's been added to the dependency package. 

https://stackblitz.com/edit/react-wvhs31?file=index.js

**Comment by diegodesouza** [comment]
I have tried to create another stackblitz from scratch, but it always gets stuck at the nanocss dependency. let me know if the one i shared is still helpful. I checked to see if the `reqNumber` is unique for the data we get, they are, so the `Pagination` should be able to see the change.

**Comment by chrishavekost** [comment]
Hey @diegodesouza - This seems related to passing mobx observables to a component that isn't a mobx observer. Adding `watchList={[providers.slice()]}` to `Pagination` should hopefully resolve this. Another approach would be something like

```javascript
const {providers} = dashboardStore; // observable value
const jsProviders = toJS(providers); // usable by pagination component

return (
  <Pagination items={jsProviders} watchList={[jsProviders]} />
);
```

Here are some links from the mobx docs talking about passing observables to non-observable components, and why/how to convert them

https://mobx.js.org/react-integration.html#dont-pass-observables-into-components-that-arent-observer

https://mobx.js.org/observable-state.html#converting-observables-back-to-vanilla-javascript-collections

https://mobx.js.org/api.html#tojs

Let me know if that helps resolve the issue.

**Comment by diegodesouza** [comment]
Unfortunately this has not yet fixed my issue.

**Comment by diegodesouza** [comment]
futre reference, adding `resetParams={[jsProviders]}` did the trick
