### ISSUE TITLE
Form - Reset single field outside <Form></Form>

### ISSUE THREAD

**Issue by diegodesouza** [Availity/availity-react#780]
## ❓Question

The design asks for a `Clear` button that is outside of the `<Form></Form>` component, with `AvForm` I was previously able to `createRef` and reset fields that way. What is the suggested way to do with the `Form`?

**Comment by diegodesouza** [comment]
I have tried `createRef()` and `useRef()` in a React function with the same warning

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Select`.
``` 
With `useRef()`

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
```

for the `Form` im using the `innerRef` prop

**Comment by chrishavekost** [comment]
Hi @diegodesouza, we do not currently implement [ref forwarding](https://reactjs.org/docs/forwarding-refs.html) in our `@availity/form` components, but it is something we are looking into. In the meantime, you should be able to do something like below and pass `yourRef` down through props. As long as you are not using `ref` as the key (`ref={yourRef}`), you should not get a warning.

Our `<Form/>` component [destructures `innerRef` and passes it to `Formik`](https://github.com/Availity/availity-react/blob/f9865f4bf40050eeb0d12e5d9b4199bcad21af87/packages/form/src/Form.js#L30) but I believe the rest of our form components will pass that prop down to the underlying (`Tag`) component (usually a `reactstrap` one that expects `innerRef`)

```js
// imports
...
const SomeComponent = () => {
  const yourFormRef = useRef(initialValue);
  const yourSelectRef = useRef(initialValue);
  ...
  return (
    <>
      <Form innerRef={yourFormRef} >
        <Select innerRef={yourSelectRef} />
      </Form>
      <Clear />
    </>
  );
};
``` 

`yourFormRef.current` should have access to the `FormikBag`, so you should be able to pass things like `yourFormRef.current.resetForm()` to your `<Clear />` component.

Let me know if that helps!

**Comment by diegodesouza** [comment]
Thanks @chrishavekost let me look into this again.

**Comment by diegodesouza** [comment]
@chrishavekost i have tried to create an example in stackblitz, but seem to have issues with an annoying `nano-css` package that even after installing the dependency, stackblitz still complains about it. Anyway here's the [example](https://react-snerqq.stackblitz.io), in my local I'm getting these errors still.
<img width="1643" alt="Screen Shot 2021-08-13 at 1 57 22 PM" src="https://user-images.githubusercontent.com/7575914/129400201-8c1f0ff2-8ca6-4bd9-b2fe-59a33f0ef514.png">
<img width="1616" alt="Screen Shot 2021-08-13 at 1 57 33 PM" src="https://user-images.githubusercontent.com/7575914/129400203-4318cd33-6fd3-499b-bbb4-c27f7a5513c7.png">

**Comment by chrishavekost** [comment]
Hey @diegodesouza I'm having trouble getting that stackblitz to load at all, can you paste snippets of the code causing each error? We have used the pattern I've described above without any issues
