### ISSUE TITLE
allow payer logo and and feedback to both be rendered in PageHeader component

### ISSUE THREAD

**Issue by nylon22** [Availity/availity-react#88]
Currently, rendering payer logo/feedback loop in `<PageHeader />` component is an either/or proposition. See: https://github.com/Availity/availity-react/blob/master/packages/page-header/PageHeader.js#L56

I have a use case where I want to show both.

**Comment by GoPro16** [comment]
I think that was just extra logic brought over from `av-react`. I don't see why we can't just remove the `!payerId` requirement in there. Although it would be a breaking change

**Comment by nylon22** [comment]
Yeah - i guess it would be breaking change if someone was passing `feedback=true` with a `payerId` prop. But seems unlikely. They'd have to be doing it on purpose _and_ not care that it doesn't work ¯\_(ツ)_/¯
