### ISSUE TITLE
Availity React  Form 1.2.1 has dependency conflict with reactstrap 9.0.1

### ISSUE THREAD

**Issue by abelchua** [Availity/availity-react#920]
## ❓Question

Hello!

It seems like availity/form can't be installed by NPM due to a upstream dependency conflict. I'm using 9.0.1 reactstrap and can't install @availity/form 1.2.1. Is there a later version of availity in NPM? Or will there be an update on the dependencies?

**Comment by jordan-a-young** [comment]
We currently use bootstrap 4 with our uikit which has kept us on v8 of `reactstrap`. Unfortunately, we do not have any current plans to upgrade support for `reactstrap@^9.0.0`.

**Comment by abelchua** [comment]
Alright thanks for letting me know. Will just stay on v8 :)
