### ISSUE TITLE
AvDate Renders Unclickable "X" in AvInput

### ISSUE THREAD

**Issue by nylon22** [Availity/availity-react#95]
I have an issue with the `<AvDateField />` export from `@availity/reactstrap-validation-date`. The underlying [AvInput that gets rendered](https://github.com/Availity/availity-react/blob/master/packages/reactstrap-validation-date/AvDate.js#L154-L164) has a red "X" that gets rendered when the input is in an invalid state. The "X" appears clickable. My expectation was the "onChange" handler would get executed with an empty value when the "X" was clicked but from what I can tell nothing gets triggered. Is this a usage issue or a bug? Please see code sandbox:

https://codesandbox.io/embed/y2znpw93k9

Notice when the user inputs a value the `handleChange` method gets triggered. When the red "X" is clicked (only appears when input is in invalid state), the `handleChange` does not get triggered.

**Comment by TheSharpieOne** [comment]
That red "x" is bootstrap (as seen here: https://getbootstrap.com/docs/4.3/components/forms/#server-side), it is just a validation indicator (100% css) and nothing more.

![x-is-bootstrap](https://user-images.githubusercontent.com/664714/55987050-af606980-5c6e-11e9-8615-321f7132a7ef.gif)

**Comment by nylon22** [comment]
thanks @TheSharpieOne

**Comment by robmcguinness** [comment]
FYI I believe this is for accessibility and should not be removed.
